version: '2'
services:
  postgres:
    image: postgres:9.6
    ports:
      - "8432:5432"
    volumes:
      - "./docker_data/postgres:/var/lib/postgresql/data"
    container_name: Will.IAM_postgres_1
  redis:
    image: redis:4-alpine
    ports:
      - "6379:6379"
    volumes:
      - "./docker_data/redis:/data"
    container_name: Will.IAM_redis_1
